<?php

/**
 * @file
 * Contains migrate_cnc.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_cnc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_cnc module.
    case 'help.page.migrate_cnc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate CNC') . '</p>';
      return $output;

    default:
  }
}
